/*
 * generated by Xtext
 */
package org.iobserve.rac.constraint.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.iobserve.rac.constraint.ui.internal.ConstraintLangActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ConstraintLangExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ConstraintLangActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ConstraintLangActivator.getInstance().getInjector(ConstraintLangActivator.ORG_IOBSERVE_RAC_CONSTRAINT_CONSTRAINTLANG);
	}
	
}
