/*
* generated by Xtext
*/
package org.iobserve.rac.constraint.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ConstraintLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/iobserve/rac/constraint/parser/antlr/internal/InternalConstraintLang.tokens");
	}
}
