/*
* generated by Xtext
*/
package org.iobserve.rac.constraint.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.iobserve.rac.constraint.services.ConstraintLangGrammarAccess;

public class ConstraintLangParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ConstraintLangGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.iobserve.rac.constraint.parser.antlr.internal.InternalConstraintLangParser createParser(XtextTokenStream stream) {
		return new org.iobserve.rac.constraint.parser.antlr.internal.InternalConstraintLangParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public ConstraintLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ConstraintLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
