/*
 * generated by Xtext
 */
package org.iobserve.rac.constraint.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ConstraintLangUiModule extends org.iobserve.rac.constraint.ui.AbstractConstraintLangUiModule {
	public ConstraintLangUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
