/**
 * generated by Xtext
 */
package org.iobserve.rac.constraint.validation;

import org.iobserve.rac.constraint.validation.AbstractConstraintLangValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ConstraintLangValidator extends AbstractConstraintLangValidator {
}
