/*
 * generated by Xtext
 */
package org.iobserve.rac.constraint.ui.contentassist

import org.iobserve.rac.constraint.ui.contentassist.AbstractConstraintLangProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ConstraintLangProposalProvider extends AbstractConstraintLangProposalProvider {
}
