/*
 * generated by Xtext
 */
package org.iobserve.rac.constraint;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ConstraintLangRuntimeModule extends org.iobserve.rac.constraint.AbstractConstraintLangRuntimeModule {

}
