/*
* generated by Xtext
*/
package org.iobserve.rac.constraint;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ConstraintLangStandaloneSetup extends ConstraintLangStandaloneSetupGenerated{

	public static void doSetup() {
		new ConstraintLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

